# Control the behaviour of the first-run setup wizard
setup:
  # When true, NeverUp2Late skips the interactive wizard and applies the default
  # update sources immediately during server start.
  skipWizard: false

# The names of the jars as they are in the server directory
filenames:
  geyser: "Geyser-Spigot.jar"
  floodgate: "floodgate-spigot.jar"
  paper: "paper.jar"

# Check interval in minutes
updateInterval: 30

# Controls automatic plugin lifecycle operations (reload/unload).
pluginLifecycle:
  # When true, NeverUp2Late will attempt to reload updated plugins automatically.
  # The default is now true so the GUI is usable without manual configuration.
  autoManage: true

# Configure how many backups NeverUp2Late keeps per update source before pruning
# the oldest entries. Set to 0 to keep all backups.
backups:
  maxCount: 5

# Ignore unstable builds (legacy location, still respected if updates.ignoreUnstable is absent)
ignoreUnstable: true

updates:
  # Ignore unstable builds for fetchers that support filtering (e.g. Paper)
  ignoreUnstable: true

  # Configure the update sources that should be checked.
  # - name: identifier used for persistence and filename lookups
  # - type: either a simple alias (e.g. "paper") or the fully qualified UpdateFetcher class name
  # - target: "server" to place the jar next to the server executable or "plugins" for the plugins directory
  # - filename: optional override for the downloaded jar name (defaults to entries under filenames.<name>)
  sources:
    - name: paper
      type: paper
      target: server
      filename: "paper.jar"
      enabled: true

    - name: geyser
      type: geyser
      target: plugins
      filename: "Geyser-Spigot.jar"
      enabled: true

    # The example below illustrates how to configure a GitHub release source.
    # Uncomment and adjust the values to track a real project.
    # - name: examplePlugin
    #   type: githubRelease
    #   target: plugins
    #   filename: "ExamplePlugin.jar"
    #   options:
    #     owner: example
    #     repository: example-plugin
    #     # assetPattern: ".*paper.*\\.jar$"   # optional regex to select a specific asset
    #     # allowPrerelease: false              # optional, defaults to false
    #     # installedPlugin: "ExamplePlugin"   # optional, used to read the installed version
