# The names of the jars as they are in the server directory
filenames:
  geyser: "Geyser-Spigot.jar"
  paper: "paper.jar"
# Check interval in minutes
updateInterval: 30
# Ignore unstable builds
ignoreUnstable: true