# The names of the jars as they are in the server directory
filenames:
  geyser: "Geyser-Spigot.jar"
  floodgate: "floodgate-spigot.jar"
  paper: "paper.jar"

# Check interval in minutes
updateInterval: 30

# Controls automatic plugin lifecycle operations (reload/unload).
pluginLifecycle:
  # When true, NeverUp2Late will attempt to reload updated plugins automatically.
  # The default is false to avoid interfering with plugins that do not support reloads.
  autoManage: false
  # Automatically load newly installed plugins when plugin lifecycle management is enabled.
  autoLoadOnInstall: true

# Ignore unstable builds (legacy location, still respected if updates.ignoreUnstable is absent)
ignoreUnstable: true

updates:
  # Ignore unstable builds for fetchers that support filtering (e.g. Paper)
  ignoreUnstable: true

  # Configure the update sources that should be checked.
  # Entries can be toggled directly from the in-game GUI.
  sources:
    paper:
      name: paper
      type: paper
      target: server
      filename: "paper.jar"
      enabled: true

    geyser:
      name: geyser
      type: geyser
      target: plugins
      filename: "Geyser-Spigot.jar"
      enabled: true

    # The example below illustrates how to configure a GitHub release source.
    # Uncomment and adjust the values to track a real project.
    # - name: examplePlugin
    #   type: githubRelease
    #   target: plugins
    #   filename: "ExamplePlugin.jar"
    #   options:
    #     owner: example
    #     repository: example-plugin
    #     # assetPattern: ".*paper.*\\.jar$"   # optional regex to select a specific asset
    #     # allowPrerelease: false              # optional, defaults to false
    #     # installedPlugin: "ExamplePlugin"   # optional, used to read the installed version
