name: NeverUp2Late
version: '1.1.1'
main: eu.nurkert.neverUp2Late.NeverUp2Late
author: nurkert
api-version: '1.21'
commands:
  nu2l:
    description: Installiert Plugins direkt aus einer URL.
    usage: "/<command> <url>"
    permission: neverup2late.install
permissions:
  neverup2late.install:
    description: Erlaubt die Nutzung des /nu2l Kommandos zum Installieren neuer Update-Quellen.
    default: op
