name: NeverUp2Late
version: '2.1.1'
main: eu.nurkert.neverUp2Late.NeverUp2Late
author: nurkert
api-version: '1.21'
commands:
  nu2l:
    description: Installs plugins directly from a URL.
    usage: "/<command> <url>"
    permission: neverup2late.install
permissions:
  neverup2late.setup:
    description: Allows completing the initial setup wizard.
    default: op
  neverup2late.install:
    description: Allows using the /nu2l command to install new update sources.
    default: op
  neverup2late.gui.open:
    description: Allows opening the graphical interface.
    default: op
  neverup2late.gui.manage:
    description: Grants all management permissions in the GUI.
    default: op
    children:
      neverup2late.gui.manage.lifecycle: true
      neverup2late.gui.manage.link: true
      neverup2late.gui.manage.settings: true
      neverup2late.gui.manage.rename: true
      neverup2late.gui.manage.remove: true
  neverup2late.gui.manage.lifecycle:
    description: Allows loading, unloading, and enabling plugins through the GUI.
    default: op
  neverup2late.gui.manage.link:
    description: Allows linking plugins with update sources.
    default: op
  neverup2late.gui.manage.settings:
    description: Allows adjusting update settings in the GUI.
    default: op
  neverup2late.gui.manage.rename:
    description: Allows renaming plugin files through the GUI.
    default: op
  neverup2late.gui.manage.remove:
    description: Allows removing plugins through the GUI.
    default: op
